import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import { connectToDatabase } from "../utils/connectMongoDb";
import RotateRightIcon from "@mui/icons-material/RotateRight";
import { useSelector } from "react-redux";

export default function Home({ posts }) {
  const loading = useSelector((state) => state.loadingState);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Cong MERN Blog</h1>
      <Layout posts={posts} />
      <div className={loading ? styles.loading : `${styles.notLoading}`}>
        <RotateRightIcon className={styles.icon} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const { db } = await connectToDatabase();
  const posts = await db
    .collection("posts")
    .find()
    .sort({ timestamp: -1 })
    .toArray();

  return {
    props: {
      posts: posts.map((post) => ({
        _id: post._id.toString(),
        creator: post.creator,
        title: post.title,
        message: post.message,
        fileSelected: post.fileSelected,
        createdAt: post.createdAt,
      })),
    },
  };
}
